Win32 (MSVC): Add and fix includes
src/cpp/core/RegexUtils.cpp:
Add missing sstream include.

src/cpp/core/file_lock/LinkBasedFileLock.cpp:
src/cpp/core/zlib/zconf.h:
unistd.h doesn't exist in MSVC.

src/cpp/core/include/core/system/System.hpp:
Including windef.h directly on MSVC leads to:
C:\Program Files(x86)\Windows Kits\8.1\Include\um\winnt.h(147) : fatal error C1189 : #error:  "No Target Architecture"
so include windows.h instead.

src/cpp/core/system/Win32OutputCapture.cpp:
Add missing io.h include.

src/cpp/core/zlib/gzguts.h:
io.h is needed on all MSVC versions.

src/cpp/r/session/graphics/RGraphicsDevDesc.hpp
Prevent 'warning C4068: unknown pragma' which happens as a result of
including R headers before Window's <cstdlib> and <cstring>