macOS: Fix Xcode link failure
Undefined symbols for architecture x86_64:
  _objc_readClassPair, referenced from:
      __ARCLite__load() in libarclite_macosx.a(arclite.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Note, this needs to be done for every executable (rsession, rpostback etc) so instead
we set LDFLAGS in build.sh when doing an Xcode build. Keeping this around as reference
meterial though.